from tkinter import *
window=Tk()
window.title("Playstation")
L1=Label(text="Welcome to your PS5",fg="white",bg="blue")
b1=Button(text="AOXE",fg="black", bg="white")
p1=Entry(fg="white",bg="black", width="80")
f1=Frame(master=window,relief=RAISED,borderwidth=9)
e1=Entry(fg="white",bg="blue",width=120)
l2=Label(text="Welcome to your PS5",fg="white",bg="blue",master=f1)
L1.pack()
b1.pack()
p1.pack()
f1.pack()
e1.pack()
l2.pack()
window.mainloop()
